// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpm71urUvNYg-aXU6KHRGqoJGeA_ybnlc',
    appId: '1:123697415981:web:8d2cfadcb3de41afa2b5a4',
    messagingSenderId: '123697415981',
    projectId: 'spotify-clone-f37bd',
    authDomain: 'spotify-clone-f37bd.firebaseapp.com',
    storageBucket: 'spotify-clone-f37bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd7a7uTGzDPbcmYh5ngu9kuhjV_bLyfSc',
    appId: '1:123697415981:android:17420114f627f372a2b5a4',
    messagingSenderId: '123697415981',
    projectId: 'spotify-clone-f37bd',
    storageBucket: 'spotify-clone-f37bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB4RpIryGbf2qFjuRUwQ9TnEjM3ZkUI1Y',
    appId: '1:123697415981:ios:75b829253ba082fda2b5a4',
    messagingSenderId: '123697415981',
    projectId: 'spotify-clone-f37bd',
    storageBucket: 'spotify-clone-f37bd.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpm71urUvNYg-aXU6KHRGqoJGeA_ybnlc',
    appId: '1:123697415981:web:8435511d3355c849a2b5a4',
    messagingSenderId: '123697415981',
    projectId: 'spotify-clone-f37bd',
    authDomain: 'spotify-clone-f37bd.firebaseapp.com',
    storageBucket: 'spotify-clone-f37bd.appspot.com',
  );
}
