// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSD31Tzm5wQYPMMMQ3q2esE7haQT8-2z0',
    appId: '1:935327747676:web:6a017ec3413269bb872099',
    messagingSenderId: '935327747676',
    projectId: 'spotify-clone-c364a',
    authDomain: 'spotify-clone-c364a.firebaseapp.com',
    storageBucket: 'spotify-clone-c364a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGF6JcF_l2m5QdrOBle3yVQkrz91bDsUE',
    appId: '1:935327747676:android:ec477dddfb1373e1872099',
    messagingSenderId: '935327747676',
    projectId: 'spotify-clone-c364a',
    storageBucket: 'spotify-clone-c364a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGZo1Z6E3Xv-pblrde_61UMJJ-T25yH0',
    appId: '1:935327747676:ios:517ae9d2fb08c8a7872099',
    messagingSenderId: '935327747676',
    projectId: 'spotify-clone-c364a',
    storageBucket: 'spotify-clone-c364a.appspot.com',
    iosBundleId: 'com.example.spotifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSD31Tzm5wQYPMMMQ3q2esE7haQT8-2z0',
    appId: '1:935327747676:web:26efd14267496e47872099',
    messagingSenderId: '935327747676',
    projectId: 'spotify-clone-c364a',
    authDomain: 'spotify-clone-c364a.firebaseapp.com',
    storageBucket: 'spotify-clone-c364a.appspot.com',
  );

}